let mournerData = [
  {
    chiefMourner: 'Alex Han',
    Mourner1: '',
    Mourner2: '',
    Mourner3: '',
    Mourner4: '',
    Mourner5: '',
    Mourner6: '',
    Mourner7: '',
    Mourner8: '',
    Mourner9: '',
  },
  {
    chiefMourner: '주현미',
    Mourner1: '',
    Mourner2: '',
    Mourner3: '',
    Mourner4: '',
    Mourner5: '',
    Mourner6: '',
    Mourner7: '',
    Mourner8: '',
    Mourner9: '',
  },
  {
    chiefMourner: '김거니',
    Mourner1: '',
    Mourner2: '',
    Mourner3: '',
    Mourner4: '',
    Mourner5: '',
    Mourner6: '',
    Mourner7: '',
    Mourner8: '',
    Mourner9: '',
  },
  {
    chiefMourner: 'Alex Han',
    Mourner1: '',
    Mourner2: '',
    Mourner3: '',
    Mourner4: '',
    Mourner5: '',
    Mourner6: '',
    Mourner7: '',
    Mourner8: '',
    Mourner9: '',
  },
  {
    chiefMourner: '주현미',
    Mourner1: '',
    Mourner2: '',
    Mourner3: '',
    Mourner4: '',
    Mourner5: '',
    Mourner6: '',
    Mourner7: '',
    Mourner8: '',
    Mourner9: '',
  },
  {
    chiefMourner: '김거니',
    Mourner1: '',
    Mourner2: '',
    Mourner3: '',
    Mourner4: '',
    Mourner5: '',
    Mourner6: '',
    Mourner7: '',
    Mourner8: '',
    Mourner9: '',
  },
];

export default mournerData;
